apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldjava-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldjava
  template:
    metadata:
      labels:
        app: helloworldjava
    spec:
      containers:
      - name: helloworldjava
        image: helloworldjava:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
